version: '3'

services:
    redis:
        container_name: redis
        networks:
            - app-network
        image: redis
        ports:
            - '6379:6379'
networks:
    app-network:
        driver: bridge
