name: Node.js CI

on:
    push:
        branches:
            - '*'

jobs:
    graphql-rest-api-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test
